export const mockPostsWithDuplicates = {
    posts: [
      {
        id: 1,
        author: "Amrita",
        authorId: 10,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health"],
      },
      {
        id: 1,
        author: "Amrita",
        authorId: 10,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health","science"],
      },
      {
        id: 2,
        author: "Juyee",
        authorId: 8,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health"],
      },
      {
        id: 3,
        author: "Anvi",
        authorId: 6,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health"],
      },
      {
        id: 3,
        author: "Anvi",
        authorId: 6,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health","startup"],
      },
      {
        id: 4,
        author: "Prashant",
        authorId: 12,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health"],
      },
    ],
  };


  export const mockValidPosts = {
    posts: [
      {
        id: 1,
        author: "Amrita",
        authorId: 10,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health"],
      },
      {
        id: 2,
        author: "Juyee",
        authorId: 8,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health"],
      },
      {
        id: 3,
        author: "Anvi",
        authorId: 6,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health"],
      },
      {
        id: 4,
        author: "Prashant",
        authorId: 12,
        likes: 960,
        popularity: 0.13,
        reads: 50361,
        tags: ["tech", "health"],
      },
    ],
  };